#GRAPHICS CONSTANTS
ACCEPTED_FILL_COLOURS = ["black", "grey", "red", "blue", "white"]

#MAZE CONSTANTS
MAZE_START_X = 10
MAZE_START_Y = 10
MAZE_CELL_SIZE_X = 15
MAZE_CELL_SIZE_Y = 15
MAZE_COLS = 40
MAZE_ROWS = 40
MAZE_COLOUR = "black"
MAZE_LINE_WIDTH = MAZE_CELL_SIZE_X // 30

#WINDOW CONSTANTS
WINDOW_SIZE = [(MAZE_CELL_SIZE_X * MAZE_ROWS + 2 * MAZE_START_X), (MAZE_CELL_SIZE_Y * MAZE_COLS + 2 * MAZE_START_Y)]
WINDOW_COLOUR = "white"