#WINDOW CONSTANTS
WINDOW_SIZE = [800, 600]

#GRAPHICS CONSTANTS
ACCEPTED_FILL_COLOURS = ["black", "grey", "red", "blue", "white"]

#MAZE CONSTANTS
MAZE_START_X = 10
MAZE_START_Y = 10
MAZE_CELL_SIZE_X = 50
MAZE_CELL_SIZE_Y = 50
MAZE_COLS = 5
MAZE_ROWS = 5
MAZE_COLOUR = "black"